name: github2dropbox
description: "Backup GitHub Data to DropBox"
inputs:
  GITHUB_TOKEN:
    description: "Access Token to GitHub"
    required: true
  DROPBOX_TOKEN:
    description: "Access Token to Dropbox"
    required: true
  DROPBOX_PATH:
    description: "With Path To Store With Dropbox"
    required: false
runs:
  using: docker
  image: Dockerfile
  env:
    DROPBOX_TOKEN: "${{ inputs.DROPBOX_TOKEN }}"
    DROPBOX_PATH: "${{ inputs.DROPBOX_PATH }}"
